import uuid
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from typing import Optional

from kyc_engine.core.security import get_current_user
from kyc_engine.services.credit_engine import CreditInput, assess_credit

router = APIRouter()


class CreditAssessRequest(BaseModel):
    applicant_id: str
    monthly_income: float = Field(..., gt=0, description="Average monthly net income (INR)")
    monthly_expenses: float = Field(..., ge=0, description="Average monthly expenses (INR)")
    existing_emis: float = Field(0, ge=0, description="Total existing EMI obligations per month (INR)")
    loan_amount_requested: float = Field(..., gt=0, description="Loan amount requested (INR)")
    loan_tenure_months: int = Field(..., gt=0, le=360, description="Loan tenure in months")
    employment_type: str = Field(..., description="salaried | self_employed | business")
    years_employed: float = Field(..., ge=0, description="Years at current employer / in business")
    kyc_request_id: Optional[str] = Field(None, description="Link to completed KYC extraction")


class FactorItem(BaseModel):
    factor: str
    impact: float


class CreditAssessResponse(BaseModel):
    assessment_id: str
    applicant_id: str
    credit_score: int
    decision: str
    max_loan_eligible: float
    proposed_emi: float
    interest_rate_band: str
    top_positive_factors: list[FactorItem]
    top_negative_factors: list[FactorItem]
    features_used: dict
    shap_values: dict
    model_version: str
    rbi_audit_note: str


@router.post(
    "/assess",
    response_model=CreditAssessResponse,
    status_code=status.HTTP_200_OK,
    summary="AI credit underwriting — XGBoost score + SHAP explanation",
)
async def assess(
    req: CreditAssessRequest,
    current_user: str = Depends(get_current_user),
):
    if req.employment_type.lower() not in ("salaried", "self_employed", "business"):
        raise HTTPException(
            status_code=422,
            detail="employment_type must be one of: salaried, self_employed, business",
        )

    inp = CreditInput(
        applicant_id=req.applicant_id,
        monthly_income=req.monthly_income,
        monthly_expenses=req.monthly_expenses,
        existing_emis=req.existing_emis,
        loan_amount_requested=req.loan_amount_requested,
        loan_tenure_months=req.loan_tenure_months,
        employment_type=req.employment_type,
        years_employed=req.years_employed,
        kyc_request_id=req.kyc_request_id,
    )

    decision = assess_credit(inp)

    return CreditAssessResponse(
        assessment_id=str(uuid.uuid4()),
        applicant_id=req.applicant_id,
        credit_score=decision.credit_score,
        decision=decision.decision,
        max_loan_eligible=decision.max_loan_eligible,
        proposed_emi=decision.proposed_emi,
        interest_rate_band=decision.interest_rate_band,
        top_positive_factors=[FactorItem(**f) for f in decision.top_positive_factors],
        top_negative_factors=[FactorItem(**f) for f in decision.top_negative_factors],
        features_used=decision.features_used,
        shap_values=decision.shap_values,
        model_version=decision.model_version,
        rbi_audit_note=(
            "Decision generated by XGBoost v2 with SHAP explainability. "
            "Model version, features, and SHAP values retained for RBI audit trail. "
            "Demo model trained on synthetic data — replace with production dataset before bank deployment."
        ),
    )
